name: Deploy REACT-APP to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_IP_ADDRESS: ${{ secrets.EC2_IP_DEV }}
          EC2_USER_NAME: ${{ secrets.EC2_USER_GIT }}
          EC2_EMAIL_ID: ${{ secrets.EC2_EMAIL_GITHUB }}

        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 400 key.pem

          # SSH into EC2 and deploy the application
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP_ADDRESS << 'EOF'
            # Set up Git user (if needed)
            git config --global user.name "$EC2_USER_NAME"
            git config --global user.email "$EC2_EMAIL_ID"

        

            # If directory doesn't exist, clone the repo
            if [ ! -d "react-app" ]; then
              git clone git@github.com:pickupbiz/react-app.git react-app
            fi

            cd react-app

            # Pull latest changes
            git pull origin main

            # Install dependencies
            npm install

            # Build the React app
            npm run build

            # Serve the app using PM2
            if pm2 list | grep -q "REACTAPP"; then
              pm2 restart REACTAPP
            else
              pm2 serve build 3000 --spa --name "REACTAPP"
            fi
          EOF

      - name: Cleanup
        run: rm key.pem
